services:
  romarr:
    build: .
    container_name: romarr
    ports:
      - "8000:8000"
    volumes:
      - ./romarr.db:/app/romarr.db
      - ./Library:/app/Library
      - ./uploads:/app/uploads
      - ./app.py:/app/app.py
      - ./routes:/app/routes
      - ./services:/app/services
      - ./Mame_XML_Full_Lists_0.285_Arcade:/app/Mame_XML_Full_Lists_0.285_Arcade:ro
      - ./No-Intro Love Pack (Standard) (2026-03-09):/app/No-Intro Love Pack (Standard) (2026-03-09):ro
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
